/* Hildana. M
 * Monogram_U3_A2.java
 * This program displays the individual's monogram using their first, last 
 * and last name 
 * April/17/2018
 */

/**
 *
 * @author himel9675
 */
public class FormMonogram_U3_A2 extends javax.swing.JFrame {

    /**
     * Creates new form FormMonogram_U3_A2
     */
    public FormMonogram_U3_A2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelEnterName = new javax.swing.JLabel();
        labelEnterMiddle = new javax.swing.JLabel();
        labelEnterLast = new javax.swing.JLabel();
        textEnterName = new javax.swing.JTextField();
        textEnterMiddle = new javax.swing.JTextField();
        textEnterLast = new javax.swing.JTextField();
        buttonCreate = new javax.swing.JButton();
        labelMonogram = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labelTitle.setText("Monogram Creator");

        labelEnterName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelEnterName.setText("Enter your first name:");

        labelEnterMiddle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelEnterMiddle.setText("Enter your middle initial:");

        labelEnterLast.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        labelEnterLast.setText("Enter your last name:");

        textEnterName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textEnterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEnterNameActionPerformed(evt);
            }
        });

        textEnterMiddle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textEnterMiddle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEnterMiddleActionPerformed(evt);
            }
        });

        textEnterLast.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        textEnterLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEnterLastActionPerformed(evt);
            }
        });

        buttonCreate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonCreate.setText("Create");
        buttonCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateActionPerformed(evt);
            }
        });

        labelMonogram.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelEnterName)
                        .addGap(46, 46, 46)
                        .addComponent(textEnterName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelEnterMiddle)
                        .addGap(26, 26, 26)
                        .addComponent(textEnterMiddle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelEnterLast)
                        .addGap(49, 49, 49)
                        .addComponent(textEnterLast))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTitle)
                        .addGap(0, 81, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelMonogram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnterName)
                    .addComponent(textEnterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEnterMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEnterMiddle))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEnterLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEnterLast))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMonogram, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textEnterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEnterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEnterNameActionPerformed

    private void textEnterMiddleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEnterMiddleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEnterMiddleActionPerformed

    private void textEnterLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEnterLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEnterLastActionPerformed

    private void buttonCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateActionPerformed
       String firstN, middleN,lastN; //variable declaration 
       
       //take the names entered 
       firstN = textEnterName.getText();
       middleN = textEnterMiddle.getText();
       lastN = textEnterLast.getText();
       
       //make name and last name lower case, but the middle name upper case
       firstN = firstN.toLowerCase();
       middleN = middleN.toUpperCase();
       lastN = lastN.toLowerCase();
       
       //print out the first letter of the first, middle, last name 
       labelMonogram.setText("Your Monogram is: " + firstN.charAt(0) + 
                  middleN.charAt(0) + lastN.charAt(0));
      
    }//GEN-LAST:event_buttonCreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMonogram_U3_A2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMonogram_U3_A2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMonogram_U3_A2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMonogram_U3_A2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMonogram_U3_A2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEnterLast;
    private javax.swing.JLabel labelEnterMiddle;
    private javax.swing.JLabel labelEnterName;
    private javax.swing.JLabel labelMonogram;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JTextField textEnterLast;
    private javax.swing.JTextField textEnterMiddle;
    private javax.swing.JTextField textEnterName;
    // End of variables declaration//GEN-END:variables
}
